version: '3.9'

services:

  postgres:
    container_name: movies-container-db
    image: "postgres:alpine"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: 'movies'
      POSTGRES_PASSWORD: 'movies'
    volumes:
      - ../../artifacts/postgres:/var/lib/postgresql/new-data/
    networks:
      - postgres

networks:
  postgres:
    driver: bridge

# version: '3.9'

# services:
#   postgres:
#     container_name: movie-reservation-system
#     image: "postgres:alpine"
#     ports:
#       - "5432:5432"
#     environment:
#       POSTGRES_USER: 'movies'
#       POSTGRES_PASSWORD: 'movies'
#     volumes:
#       - ../../artifacts/postgres:/var/lib/postgresql/data/
#     networks:
#       - postgres

# networks:
#   postgres:
#     driver: bridge
